---
- name: Install Nginx
  become: yes
  apt: name=nginx state=latest

- name: Start Nginx
  become: yes
  service: name=nginx state=started enabled=true

- name: Creation des apps nginx
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ domain }}_{{ item.env }}
  with_items:
    - {env: production, port: 80, node_port: 5000}
    # - {env: staging, port: 7456, node_port: 5001}

- name: Delete default nginx file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Activation du domaine {{ domain }}
  with_items:
    - production
    # - staging
  file: src=/etc/nginx/sites-available/{{ domain }}_{{ item }} dest=/etc/nginx/sites-enabled/{{ domain }}_{{ item }} state=link
  notify: nginx reload

- name: restart nginx
  service: name=nginx state=restarted
...