---
- name: Installation des serveurs web
  hosts: web
  remote_user: root
  vars: 
    user: deploy
    domain: dmkreation.fr
  roles:
    # - starter
    # - deployer
    # # Attention, l'app nodeJS doit être en service via p2m avant d'installer nginx
    - nginx
    # - mysql
    # - node
...