---
- name: Install Mysql-server
  apt:
    update_cache: yes
    pkg: 
      - mysql-client
      - python3-dev
      - python3-mysqldb
      - python-mysqldb
      - mysql-server

- name: Remove all anonymous user
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Create a new database with name '{{db_name}}'
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create database {{ user }} with all database privileges
  mysql_user:
    name: "{{ user }}"
    password: "{{ my_db_password }}"
    priv: '{{db_name}}.*:ALL'
    state: present

...