---
- name: Install nvm
  git: "repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v{{ nvm_version }}"
  tags: nvm

- name: Source nvm in bash profile
  lineinfile: >
    dest=~/.{{ item }}
    line="source ~/.nvm/nvm.sh"
    create=yes
  tags: nvm
  with_items:
    - bashrc
    - profile

- name: "Install node and set version {{ node_version }}"
  become: yes
  become_user: root
  shell: "source /root/.nvm/nvm.sh && nvm install {{ node_version }}" 
  args:
    executable: /bin/bash

- name: Install "pm2" node.js package globally.
  npm:
    name: pm2
    global: yes
...


